import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar, Footer } from "@/components";
import localfont from "next/font/local";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NanumBarunGothicLight = localfont({
  src: [
    {
      path: "../public/fonts/NanumBarunGothicLight.ttf",
      weight: "normal",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${NanumBarunGothicLight.className}`}>
        <Providers>
          <Navbar />
          <div className="">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

const FontLocalLayout = (props: Props) => {
    return (<>
    <Navbar />
    <div className={blackHanSans.className}>{props.children}</div>
    <Footer />
    </>
    );
};

export default FontLocalLayout;

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: {
//     children: React.ReactNode;
// }) {
//     return (
//         <html lang="en" className={Cafe24Ssurround.className}>
//             <body className={inter.className}>
//                 <Navbar />
//                 {children}
//                 <Footer />
//             </body>
//         </html>
//     );
// }
